services:

  catalogdb:
    image: postgres:17-alpine
    networks:
        pg_network:
  
  basketdb:
    image: postgres:17-alpine
    networks:
        pg_network:
  distributedcache:
    image: redis
   

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
      
    networks: 
       pg_network:

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile
     
    networks: 
       pg_network:
   
  adminer:
    image: adminer
    depends_on: 
         -  catalogdb
    networks:
       pg_network:

  seq:
    image: datalust/seq:latest
    container_name: seq
    restart: unless-stopped
    ports:
      - "5341:80"
    environment:
      - ACCEPT_EULA=Y
      - SEQ_PASSWORD=123456
      - SEQ_FIRSTRUN_ADMINUSERNAME=admin
      
    volumes:
      - seq_data:/data
   

secrets:
  postgres_user:
    file: ./Secrets/postgres_user.txt         
  postgres_password:
    file: ./Secrets/postgres_password.txt
  postgres_catalogdb:
    file: ./Secrets/catalogDb_name.txt
  postgres_basketdb:
    file: ./Secrets/basketDb_name.txt
  # github_token:
  #   file: ./github_token.txt


volumes:
  postgres_catalog:
  postgres_basket:
  seq_data:

networks:
  pg_network:
    driver: bridge
