services:
    
    catalogdb:
        container_name: catalogdb
        restart: always
         
        environment:
          POSTGRES_USER_FILE: /run/secrets/postgres_user         
          POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password 
          POSTGRES_DB_FILE: /run/secrets/postgres_catalogdb

        secrets:
          - postgres_user
          - postgres_password
          - postgres_catalogdb
        ports:
            - "5432:5432"
        volumes:
          - ./postgres_catalogDb:/var/lib/postgresql/data/
   
    basketdb:
        container_name: basketdb
        restart: always
         
        environment:
          POSTGRES_USER_FILE: /run/secrets/postgres_user         
          POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password 
          POSTGRES_DB_FILE: /run/secrets/postgres_basketdb

        secrets:
          - postgres_user
          - postgres_password
          - postgres_basketdb
        ports:
            - "5433:5432"
        volumes:
          - ./postgres_basketDb:/var/lib/postgresql/data/

    adminer:
         restart: always
         ports:
             - 8080:8080
    
    distributedcache:
        container_name: distributedcache
        restart: always
        ports:
            - "6379:6379"
       

    catalog.api:
      environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - ASPNETCORE_HTTP_PORTS=8080
          # - ASPNETCORE_HTTPS_PORTS=8081
          - ConnectionStrings__Database=Host=catalogdb;Port=5432;Database=CatalogDb;Username=postgres;Password=postgres;Include Error Detail=true
      depends_on:
           - catalogdb
      ports:
          - "6000:8080"
          # - "6060:8081"
      volumes:
          - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
          - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    
    basket.api:
      environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - ASPNETCORE_HTTP_PORTS=8080
          # - ASPNETCORE_HTTPS_PORTS=8081
          - ConnectionStrings__Database=Host=basketdb;Port=5432;Database=BasketDb;Username=postgres;Password=postgres;Include Error Detail=true
          - ConnectionStrings__Redis=distributedcache:6379 
      depends_on:
           - basketdb
           - distributedcache
      ports:
          - "6001:8080"
          # - "6061:8081"
      volumes:
          - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
          - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    